OOP school library: add Person, Student and Teacher classes
hasnatali1947/-OOP_school_library pull request #1
Opened 2023-06-19 18:39 UTC by hasnatali1947

- Implement classes and objects in Ruby.
- Implement encapsulation and inheritance with Ruby.
- Run a program using the command line.

2023-06-19 18:42 UTC, TedLivist reviewed
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @hasnatali1947,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly set up linters for this project. Additionally, kindly ensure all the sections in your README have links in the Table of Contents that lead to them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-20 10:03 UTC, brytebee requested changes
Hi, @hasnatali1947 👋,

##

### Highlights💡
- Great use of the Ruby style guide.✔️
- Great use of Classes and Ruby OOP.✔️
- Good commit message.✔️ 
- Good PR Summary.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 10:03 UTC, brytebee commented on person.rb
> +  end
The logic @age >= 18 already is contained in the @of_age?. Rather than repeat the logic, kindly call the method name here. 

This makes your codebase DRY.

```ruby
def can_use_services?
    @age >= 18 || @parent_permission
end
```

2023-06-20 10:03 UTC, brytebee commented on person.rb
> +    return true if @age >= 18
- [ ] **Optional:**

`return true if @age >= 18` === `@age >= 18`

This code is cleaner.

2023-06-20 10:27 UTC, Ibizugbe approved these changes
Hi @hasnatali1947 👋👋, 

![VeryNiceNiceGIF](https://github.com/hasnatali1947/-OOP_school_library/assets/64643995/7e3fb1ed-9a0e-4460-b917-1880d8e20ce1)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅

- [x] `can_use_service` method has been refactored as requested by the previous reviewer👍.
- [x] Linters are passing👍.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 15:29 UTC, merged